# Generated by Django 4.0.3 on 2022-03-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='Student',
        ),
    ]
