# Generated by Django 4.0.3 on 2022-03-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0002_rename_studentmodel_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentModel',
        ),
    ]
