# Generated by Django 4.0.3 on 2022-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0003_rename_student_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
