# Generated by Django 4.0.3 on 2022-03-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
