# Generated by Django 4.0.1 on 2022-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_character_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
